dist: trusty
sudo: required

language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

before_install:
    - sudo apt-get --yes remove --purge libcurl4-gnutls-dev
    - sudo apt-get --yes install libcurl4-openssl-dev
    - curl --version

install:
    - composer self-update
    - composer install -o

script:
    - vendor/bin/phpunit -c phpunit.xml.dist
