sudo: false

language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

addons:
  apt:
    packages:
      libcurl3-gnutls

before_install:
    - curl --version

install:
    - composer self-update
    - composer install -o

script:
    - vendor/bin/phpunit -c phpunit.xml.dist
