sudo: required

language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

addons:
  apt:
    packages:
      libcurl4-openssl-dev

before_install:
    - sudo apt-get remove --yes --purge libcurl4-gnutls-dev
    - sudo apt-get install --yes libcurl4-openssl-dev
    - curl --version

install:
    - composer self-update
    - composer install -o

script:
    - vendor/bin/phpunit -c phpunit.xml.dist
